### ISSUE TITLE
Breaks in Jest test when having nest styles with dynamic parts

### ISSUE THREAD

**Issue by eskimoblood** [cssinjs/react-jss#196]
My styles looks like this: 

```
const style = {
    border: 0,
    background: 'none',
    padding: [2, 5, 0],
    margin: [0, 2],
    '& i': {
        margin: 0,
    },
    '&:hover': {
        borderBottom: 'solid 1px',
        borderColor: ({ theme }) => theme.color.primary.base,
    },
}
```
This breaks in Jest test when rendering the component with Enzyme using shallow or mount with the following error: 
```
    TypeError: Cannot read property 'selectorText' of undefined
```

and this  stack trace: 

```
at DomRenderer.getUnescapedKeysMap (node_modules/jss/lib/renderers/DomRenderer.js:159:41)
      at RuleList.link (node_modules/jss/lib/RuleList.js:206:45)
      at StyleSheet.link (node_modules/jss/lib/StyleSheet.js:204:32)
      at StyleSheet.attach (node_modules/jss/lib/StyleSheet.js:57:51)
      at Jss.manage (node_modules/react-jss/lib/createHoc.js:201:43)
      at Jss.componentWillMount (node_modules/react-jss/lib/createHoc.js:208:14)
      at ReactShallowRenderer._mountClassComponent (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:134:22)
      at ReactShallowRenderer.render (node_modules/react-test-renderer/cjs/react-test-renderer-shallow.development.js:100:14)
      at node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:285:35
      at withSetStateAllowed (node_modules/enzyme-adapter-utils/build/Utils.js:95:16)
      at Object.render (node_modules/enzyme-adapter-react-16/build/ReactSixteenAdapter.js:284:68)
      at new ShallowWrapper (node_modules/enzyme/build/ShallowWrapper.js:119:22)
      at ShallowWrapper.wrap (node_modules/enzyme/build/ShallowWrapper.js:1648:16)
      at ShallowWrapper.<anonymous> (node_modules/enzyme/build/ShallowWrapper.js:1718:26)
      at ShallowWrapper.single (node_modules/enzyme/build/ShallowWrapper.js:1620:25)
      at ShallowWrapper.dive (node_modules/enzyme/build/ShallowWrapper.js:1710:21)
      at Object.<anonymous> (test/src/components/common/IconTabBar.spec.js:22:9)
```
It seems that the following lines cause the problem: 

```
'&:hover': {
        borderBottom: 'solid 1px',
        borderColor: ({ theme }) => theme.color.primary.base,
    },
```

using just:
```
        borderBottom: 'solid 1px',
        borderColor: ({ theme }) => theme.color.primary.base,
```
or 
```
'&:hover': {
        borderBottom: 'solid 1px',
    },
```
fix the problem, so having a nested rule with a dynamic styles seems to cause the problem..

**Comment by kof** [comment]
Can you please also add a reproducible example on codesandbox so that we make sure we can reproduce it as soon as me or someone else has time?

**Comment by eskimoblood** [comment]
As it seems only happen in tests, how would codesandbox help here, is there any playground that would be much better for this case?

**Comment by kof** [comment]
is it not possible to use jest on codesandbox?

**Comment by eskimoblood** [comment]
I have no idea, never used it and I can't see how to run the tests there

**Comment by kof** [comment]
You should be able to require jest and run the tests from the api very easily

**Comment by eskimoblood** [comment]
Ok here it is: https://codesandbox.io/s/m1k1lm878 
Unfortunately the error does not appear

**Comment by kof** [comment]
Is it using JsDom in that case? If it is using the browser dom, it is probably something missing in JsDOM

**Comment by kof** [comment]
Also, have you tried VirtualRenderer? in case you don't need the actual css attached.

**Comment by kof** [comment]
Normally VirtualRenderer would be used on the server, but in case of jest I assume it adds dom globals to the context, so JSS doesn't use VirtualRenderer automatically and tries to behave same like with real DOM, which in that case probably just misses CSSOM parts.

**Comment by eskimoblood** [comment]
So how to use `VirtualRenderer` in this example?

**Comment by kof** [comment]
there is virtual: true option for jss

**Comment by kof** [comment]
@eskimoblood did it work with VirtualRenderer?

**Comment by eskimoblood** [comment]
Argh totally forgot about this cause I couldn't figure out how to enable the VirtualRenderer, could you please point me to the docs on how to do this.

**Comment by kof** [comment]
http://cssinjs.org/js-api?v=v9.8.0#setup-jss-instance

**Comment by kof** [comment]
I guess you figured out how to use VirtualRenderer, if not please reopen.
